Algoritmo "Desafio 05"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Elberth Moraes
// Descrição   : calcular pontos dos times
// Autor(a)    : Alysson Araújo Duarte
// Data atual  : 09/02/2022



Var
nome: caracter
pontos: inteiro
vitorias: inteiro
empates: inteiro


Inicio
          vitorias <- 3
          empates <- 10
   pontos <- ( vitorias * 3) + empates
         escreval (" O time ", nome, " está com ", pontos, " pontos")
Fimalgoritmo